- hosts: localhost
  gather_facts: yes
  tasks:
    - debug: var=ansible_date_time

    - set_fact:
        config_datetime: "{{ansible_date_time.iso8601_basic_short}}"

- hosts: all
  gather_facts: False
  collections:
    - arubanetworks.aoscx
  tasks:
    - debug: msg="the current date is {{ hostvars['localhost']['config_datetime']}}"

    # - name: Copy running-config to checkpoint
    #   aoscx_checkpoint:
    #     source_config: 'running-config'
    #     destination_config: "ANSIBLE_{{ hostvars['localhost']['config_datetime']}}"

- hosts: all
  gather_facts: False
  collections:
    - arubanetworks.aoscx
  vars:
      ansible_connection: network_cli
  tasks:
    - name: Backup checkpoint via CLI
      aoscx_command:
        commands:
          - copy running check ANSIBLE_{{ hostvars['localhost']['config_datetime']}}
    - name: Backup Config
      aoscx_config:
        backup: True
        backup_options:
          filename: "{{inventory_hostname}}.txt"
          dir_path: ../      
#  - hosts: all
#    gather_facts: False
#    collections:
#      - arubanetworks.aoscx
#    vars:
#      ansible_connection: network_cli
#    tasks:
#      - name: Generate Device Specific Config via Template
#        template:
#          src: cx_access.j2
#          dest: ../tmp/{{inventory_hostname}}_tmp.txt

#      - name: Execute Generated Config via SSH
#        aoscx_config:
#          src: ../tmp/{{inventory_hostname}}_tmp.txt
#          back