- hosts: localhost
  gather_facts: yes
  tasks:
    - debug: var=ansible_date_time

    - set_fact:
        config_datetime: "{{ansible_date_time.iso8601_basic_short}}"

    - name: Generate Device Specific Config via Template
      template:
        src: last_checkpoint.j2
        dest: ../tmp/{{inventory_hostname}}_tmp.txt


- hosts: all
  gather_facts: False
  collections:
    - arubanetworks.aoscx
  tasks:
    - debug: msg="the current date is {{ hostvars['localhost']['config_datetime']}}"

- hosts: all
  gather_facts: False
  collections:
    - arubanetworks.aoscx
  vars:
      ansible_connection: network_cli
  tasks:
    - name: Backup checkpoint BEFORE Ansible 
      aoscx_command:
        commands:
          - copy running check ANSIBLE_{{ hostvars['localhost']['config_datetime']}}

    - name: Generate Device Specific Config via Template
      template:
        src: cx_access.j2
        dest: ../tmp/{{inventory_hostname}}_tmp.txt

    - name: Copy Config to switch
      aoscx_config:
        src: ../tmp/{{inventory_hostname}}_tmp.txt

    - name: Backup Config Locally 
      aoscx_config:
        backup: True
        backup_options:
          filename: "{{inventory_hostname}}.txt"
          dir_path: ./configs      
#  - hosts: all
#    gather_facts: False
#    collections:
#      - arubanetworks.aoscx
#    vars:
#      ansible_connection: network_cli
#    tasks:
#      - name: Generate Device Specific Config via Template
#        template:
#          src: cx_access.j2
#          dest: ../tmp/{{inventory_hostname}}_tmp.txt

#      - name: Execute Generated Config via SSH
#        aoscx_config:
#          src: ../tmp/{{inventory_hostname}}_tmp.txt
#          back