- hosts: localhost
  gather_facts: yes
  tasks:
    - debug: var=ansible_date_time

    - set_fact:
        config_datetime: "{{ansible_date_time}}"

- hosts: all
  gather_facts: False
  collections:
    - arubanetworks.aoscx
  tasks:
    - debug: msg="the current date is {{ hostvars['localhost']['config_datetime']}}"

#     - debug: var=TFTP_SERVER

#    - name: Copy running-config to startup-config
#      aoscx_checkpoint:
#        source_config: 'running-config'
#        destination_config: 'startup-config'
#fdafdf
# - hosts: all
#   gather_facts: False
#   collections:
#     - arubanetworks.aoscx
#   vars:
#     ansible_connection: network_cli
#   tasks:
#     - name: generate vlans based on template
#       template:
#         src: cx_access.j2
#         dest: ./generated_vlans.txt

#     - name: Execute Generated Config via SSH
#       aoscx_config: