all:
  children:
    aoscx:
      vars:
        ansible_user: admin      
        ansible_network_os: arubanetworks.aoscx.aoscx
        ansible_connection: arubanetworks.aoscx.aoscx
        ansible_aoscx_validate_certs: False
        ansible_aoscx_use_proxy: False
        ansible_acx_no_proxy: True
      hosts:
        switch115:
          ansible_host: 66.60.164.115
          ansible_password: $uGar1$nap!1
        # switch116:
        #   ansible_host: 66.60.164.116
        #   ansible_password: $uGar1$nap!2
        # switch117:
        #   ansible_host: 66.60.164.117
        #   ansible_password: $uGar1$nap!3  