all:
  children:
    roseville-site:
      vars:
        mgmt_gateway: 192.168.0.1
        hostname: Access-6200-115
        uplink_vlan_ip: 172.25.5.115
        default_route: 172.25.5.251
        dns_server: 10.80.2.219
        ntp_server: 10.80.2.219
      children:
        aoscx:
          vars:
            ansible_user: admin      
            ansible_network_os: arubanetworks.aoscx.aoscx
            ansible_connection: arubanetworks.aoscx.aoscx
            ansible_aoscx_validate_certs: False
            ansible_aoscx_use_proxy: False
            ansible_acx_no_proxy: True
          hosts:
            Access-6200-115:
              ansible_host: 66.60.164.115
              mgmt_ip: 192.168.0.215
            Access-6200-116:
              ansible_host: 66.60.164.116
              mgmt_ip: 192.168.0.216
            Access-6200-117:
              ansible_host: 66.60.164.117
              mgmt_ip: 192.168.0.217
